### ISSUE TITLE
Edit items

### ISSUE THREAD

**Issue by Morgy93** [jjuback/gc-excelviewer#2]
Looks awesome, but will it ever be able to edit the items?
Or is it just not possible for whatever reason?

**Comment by jjuback** [comment]
It is certainly possible, and after additional read-only features are in place, that's likely the next task.

**Comment by sweiner** [comment]
John, have you run into any security roadblocks trying to implement file editing in the preview?  I was looking into doing something similar for a different extension, but I wasn't sure if it was possible.

**Comment by jjuback** [comment]
I recommend downloading the insiders build and taking a look at the new proposed API for Webview (see the release notes for version 1.21), as the current TextDocumentContentProvider model looks like it will be phased out eventually. The only security issue I had with the Webview API was that I could no longer use XmlHttpRequest with the file: URI scheme, so I worked around it by performing file access in my localhost web server. But they are going to remove the restriction for the vscode-resource: scheme, so at some point I will be able to use that instead of file: to open workspace files with XHR.

**Comment by jjuback** [comment]
UPDATE: Version 2.1.23 uses the Webview API, which sets the stage for editable previews. There are many details that still need to be ironed out, however.

**Comment by jjuback** [comment]
It took a while, but there is now a pre-release version (4.1.51) that supports editing of CSV and Excel files.

**Comment by jjuback** [comment]
Editing features are now part of the latest stable version (4.2.53).
