### ISSUE TITLE
[Feature Request] Line numbers (including filtering mode)

### ISSUE THREAD

**Issue by neooleg** [jjuback/gc-excelviewer#42]
Hi @jjuback,

thanks a lot for such great extension.

Is this possible to add line number event for filtered view?

**Comment by jjuback** [comment]
In version 2.0.20, you can change the `csv-preview.lineNumbers` setting to true. Note that when you are in filtered view for a CSV file, the line numbers will still be displayed sequentially, 1 through N. This is because filtering generates a new CollectionView, which does not have the original line numbers. This behavior differs from the way the extension (moreover, its underlying FlexSheet control) handles Excel files. In that case, filtering is achieved by marking individual rows as visible or not depending upon the filter criteria. The actual data source is unchanged.
