### ISSUE TITLE
Selecting "CSV (semicolon)" file type should be work

### ISSUE THREAD

**Issue by ElCondor1969** [jjuback/gc-excelviewer#63]
If you open a CSV file separated by semicolon and then you select in the editor the file type "CSV (semicolon)" for it, the extension should work anyway while showing the preview and consider the character ";" as separator, ignoring what is set in the option "csv-preview.separator".
Currently, however, specifying the file type "CSV (semicolon)" the preview does not work and the following error message is shown: "Active editor doesn't show a CSV or plain text document."

**Comment by jjuback** [comment]
The language id "csv (semicolon)" is contributed by another third-party extension (Rainbow CSV). I was not aware of this extension until today. This will be fixed in the next maintenance release.

**Comment by mechatroner** [comment]
Hello, @jjuback, I am the author of Rainbow CSV. Are you planning to rely on language id? If you do, it is "CSV (semicolon)" now, with "CSV" capitalized.

**Comment by jjuback** [comment]
@mechatroner I just released a new version (2.1.23) that handles both your language ids (upper case) and mine (lower case). Note that the Microsoft [documentation](https://code.visualstudio.com/docs/languages/identifiers#_new-identifier-guidelines) recommends using lower case.

**Comment by mechatroner** [comment]
Thank you @jjuback ! I haven't seen this recommendation before.
Originally I used lowercase language ids, but then switched to uppercase because I though that this would be more clear for users: I had to provide uppercase aliases anyway which are shown in the lower right corner, and people will associate them with real language ids which are needed sometimes to provide filetype -> language_id associations. 
If I add more language ids, I will inform you about this.
And I will mention Excel Viewer in Rainbow CSV docs since both extensions are somewhat integrated now.
And BTW thank you for the cool project! I've used one or two technical ideas from gc-excelviewer to create csv preview for content transformation, but my approach is totally different since there is no visual transformation controls and I don't plan to add any. Instead there is a single entry field for SQL-like RBQL query that does such transformation.

**Comment by mechatroner** [comment]
Hi @jjuback ! Just to let you know, I've added 7 new separators/languages to my Rainbow CSV extension:
csv (tilda)
csv (caret)
csv (colon)
csv (double quote)
csv (equals)
csv (dot)
csv (hyphen)
I think these separators are much less popular than comma, tab, semicolon and pipe; but it you want you can add special handling for these language ids too. All these grammars have the most simple form, just like "csv(pipe)".
