### ISSUE TITLE
Multi-line CSV records not displayed

### ISSUE THREAD

**Issue by The-MAZZTer** [jjuback/gc-excelviewer#79]
Some variants of CSV allow for embedded newlines in records as long as the field is quoted.

For example:

```
0,1,2,"Long line
with embedded
newlines",3,4
```

Records like this do not seem to show up properly. I get two records displayed for the last two lines in this case, and the first line seems to not show up at all.

**Comment by fguchelaar** [comment]
I took a stab at this and created a Pull Request #90 that implements the support of multiline records.

Note that your provided example will not result in multiple lines in a row, since there is only one line and it will use that line as the header row. But for files with multiple rows, it should work.

**Comment by jjuback** [comment]
@fguchelaar I had to tweak your regex so that it would recognize quoted empty fields. Your PR is included in version 2.1.27.
