### ISSUE TITLE
about excelviewer of vscode

### ISSUE THREAD

**Issue by zhaohaixin** [jjuback/gc-excelviewer#9]
i can't open preview the .csv file ,if i open preview ,it will stop with black board,no data.thank you!
vscode:1.52

**Comment by jjuback** [comment]
If you upload your file I can take a look and try to reproduce the problem. Thank you.

**Comment by zhaohaixin** [comment]
just like these,sorry there is something wrong ,i can't commit the file.
![pic3](https://cloud.githubusercontent.com/assets/21098141/18735756/fddbb6fe-80b2-11e6-85c0-1c1148aeaf53.PNG)
![pic1](https://cloud.githubusercontent.com/assets/21098141/18735713/93a41c4a-80b2-11e6-9591-d6955065906e.PNG)
![pic2](https://cloud.githubusercontent.com/assets/21098141/18735711/92c42ed2-80b2-11e6-9481-4716b525f346.PNG)

**Comment by jjuback** [comment]
I created the first 6 lines of your screenshot and was able to get it to display correctly (with csv-preview.hasHeaders set to false).

[A_summary.txt](https://github.com/jjuback/gc-excelviewer/files/488245/A_summary.txt)

Does this short version work for you? Also, can you try renaming your file with a .txt extension and uploading it here?

**Comment by zhaohaixin** [comment]
I have download the file A_summary.txt,but also i can't open priview,the problem also is a black board.
This is my file .
[A_summary.txt](https://github.com/jjuback/gc-excelviewer/files/497502/A_summary.txt)

**Comment by jjuback** [comment]
I can view the file you uploaded, so the problem is something else. Are you behind a firewall or proxy server? The extension needs to access the Wijmo CDN, as shown in this Fiddler image:

![image](https://cloud.githubusercontent.com/assets/18399724/18994003/ea03b54a-86f3-11e6-8843-d278273dd472.png)

Check your HTTP traffic using Fiddler or a similar tool. I think this is the cause of your issue.

**Comment by zhaohaixin** [comment]
Yes,thanks.My commpany is close the public net .

发自我的 iPhone
